# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(blank=True, max_length=200)),
                ('attribute_value', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_hstore.fields.DictionaryField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microarray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_hstore.fields.DictionaryField(blank=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_hstore.fields.DictionaryField(db_index=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='microarrays',
            field=models.ManyToManyField(to='articles.Microarray'),
        ),
    ]
