# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microarrays', models.ManyToManyField(to='articles.Microarray')),
            ],
        ),
    ]
