# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160830_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
