# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160830_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowModel',
        ),
    ]
