# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160830_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAttributeValueInSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Sample')),
                ('unificated_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.UnificatedSamplesAttributeValue')),
            ],
        ),
        migrations.RemoveField(
            model_name='oldsampleattributevalue',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='oldsamplesattributename',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='sampleattributevalue',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sampleattributevalue',
            name='unificated_value',
        ),
        migrations.AddField(
            model_name='samplesattributenameinexperiment',
            name='old_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OldSampleAttributeValue',
        ),
        migrations.DeleteModel(
            name='OldSamplesAttributeName',
        ),
        migrations.DeleteModel(
            name='SampleAttributeValue',
        ),
    ]
