# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160831_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesattributenameinexperiment',
            name='unificated_name',
        ),
        migrations.DeleteModel(
            name='UnificatedSamplesAttributeName',
        ),
    ]
