# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160906_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleattributevalueinsample',
            old_name='unificated_name_value',
            new_name='unificated_value',
        ),
        migrations.AddField(
            model_name='sampleattributevalueinsample',
            name='unificated_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.SamplesAttributeNameInExperiment'),
            preserve_default=False,
        ),
    ]
