# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20160906_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='fictional_field',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
