# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_sample_fictional_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleAttributeValueInSample',
            new_name='SampleAttribute',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='fictional_field',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample_attribute_names',
            field=models.ManyToManyField(blank=True, to='articles.SamplesAttributeNameInExperiment'),
        ),
    ]
