# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20160908_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesattributenameinexperiment',
            name='unificated_name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='sample_attribute_names',
        ),
        migrations.AddField(
            model_name='sampleattribute',
            name='old_name',
            field=models.CharField(default='<empty>', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unificatedsamplesattributevalue',
            name='unificated_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.UnificatedSamplesAttributeName'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleattribute',
            name='unificated_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.UnificatedSamplesAttributeName'),
        ),
        migrations.DeleteModel(
            name='SamplesAttributeNameInExperiment',
        ),
    ]
