# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 02:35
from __future__ import unicode_literals

from django.db import migrations
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20160912_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardname',
            name='mesh_id',
        ),
        migrations.RemoveField(
            model_name='standardvalue',
            name='mesh_id',
        ),
        migrations.AddField(
            model_name='standardname',
            name='additional_info',
            field=django_hstore.fields.DictionaryField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='standardvalue',
            name='additional_info',
            field=django_hstore.fields.DictionaryField(blank=True, db_index=True, null=True),
        ),
    ]
