# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20160913_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='unificatedsamplesattributename',
            name='synonyms',
            field=models.ManyToManyField(to='articles.UnificatedSamplesAttributeName'),
        ),
    ]
