# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20160913_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='unificatedsamplesattributevalue',
            name='synonyms',
            field=models.ManyToManyField(to='articles.UnificatedSamplesAttributeValue'),
        ),
        migrations.AlterField(
            model_name='sampleattribute',
            name='old_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sampleattribute',
            name='old_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='unificatedsamplesattributename',
            name='synonyms',
            field=models.ManyToManyField(to='articles.UnificatedSamplesAttributeName'),
        ),
    ]
