# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20161015_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.IntegerField(default=0)),
                ('unificated_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.StandardName')),
            ],
        ),
    ]
