# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_columnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnorder',
            name='show_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='columnorder',
            name='column_order',
            field=models.IntegerField(default=99),
        ),
    ]
