# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20170114_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnorder',
            name='show_at_all',
            field=models.BooleanField(default=True),
        ),
    ]
